@base_url = http://192.168.1.170:3000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZTExMDRiZi04NjkxLTQyYTEtOTE2Zi0zM2U1MDA2MzVhMjMiLCJlbWFpbCI6Im1hdGhpZXVAZXhhbXBsZS5jb20iLCJpYXQiOjE3NDc0NzcyMzMsImV4cCI6MTc0NzQ4MDgzM30.PM0HpcHlyDZDj9z3Q2al0g4zCWIl2gdB0VOHTHPHURM

@item_id = 19275c24-7375-4336-bd6d-91de971990c4

@list_id = 5418022d-8a50-4dd3-bc05-de233110a2b6

@category_id = 50a19592-94b5-4baf-8a01-8edbb467954f

###  
# 1) Inscription
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "email": "mathieu@example.com",
  "username": "mathieu23",
  "password": "MonSuperMdp!"
}

###  
# 2) Login
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "mathieu@example.com",
  "password": "MonSuperMdp!"
}

###  
# On récupère le token automatiquement
> {% 
    const json = JSON.parse(response.body);
    client.global.set("token", json.access_token);
%}

###  
# 3) Récupérer le profil
GET {{base_url}}/users/me
Authorization: Bearer {{token}}


###
# 1) Créer une catégorie
POST {{base_url}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Plantes"
}



###
# 2) Lister toutes les catégories
GET {{base_url}}/categories
Authorization: Bearer {{token}}

###
# 3) Récupérer une catégorie précise
GET {{base_url}}/categories/{{category_id}}
Authorization: Bearer {{token}}

###
# 4) Mettre à jour la catégorie
PATCH {{base_url}}/categories/{{category_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "outdoor-sports"
}

###
# 5) Supprimer la catégorie
DELETE {{base_url}}/categories/{{category_id}}
Authorization: Bearer {{token}}

###  
# 4) Créer un Top (List)
POST {{base_url}}/lists
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Top 5 Films",
  "category": "50a19592-94b5-4baf-8a01-8edbb467954f"
}

###  
# 5) Lister tous mes Tops
GET {{base_url}}/lists
Authorization: Bearer {{token}}

###  
# 6) Récupérer un Top précis (remplace list_id)


GET {{base_url}}/lists/{{list_id}}
Authorization: Bearer {{token}}

###  
# 7) Mettre à jour un Top
PATCH {{base_url}}/lists/{{list_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Top 5 Films Cultes"
}

###  
# 8) Supprimer un Top
DELETE {{base_url}}/lists/{{list_id}}
Authorization: Bearer {{token}}

###  
# 9) Ajouter un Item à un Top
POST {{base_url}}/lists/{{list_id}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "patate",
  "rank": 3
}

###  
# 10) Lister les Items d’un Top
GET {{base_url}}/lists/{{list_id}}/items
Authorization: Bearer {{token}}

###  
# 11) Mettre à jour un Item

PATCH {{base_url}}/lists/{{list_id}}/items/{{item_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rank": 2
}

###  
# 12) Supprimer un Item
DELETE {{base_url}}/lists/{{list_id}}/items/{{item_id}}
Authorization: Bearer {{token}}


=

### Recherche image Unsplash
GET {{base_url}}/lookup?q=apple





###
# Ajouter la catégorie Food avec image locale
POST {{base_url}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "food",
  "imageUrl": "/static/images/categories/food.png"
}
